#!/usr/bin/env bash
# render.sh — build the programmer-guide PDFs from their .md via pandoc
# (tufte-handout .tex) + tectonic, in the explainer's tufte style: a full
# title page (generated per doc below), no running heads, centered page
# numbers, heading-orphan protection (see axona-doc-preamble.tex).
#
#   ./render.sh                          # render all five
#   ./render.sh Quick-Start-v4.22.0      # render one (basename, no extension)
#
# Requires: pandoc + tectonic on PATH (no system TeX Live needed — tectonic is
# self-contained and auto-fetches tufte-latex). Menlo font (macOS) for code.
set -euo pipefail
cd "$(dirname "$0")"

VERSION="v4.38.0"
DATE="2026-07-23"

DOCS=(
  "Quick-Start-v4.38.0"
  "Axona-Programmer-Guide-v4.38.0"
  "Axona-API-Reference-v4.38.0"
  "Axona-Services-Guide-v4.38.0"
  "Axona-AI-Grounding-v4.30.0"
)
[ "$#" -gt 0 ] && DOCS=("$@")

# Per-doc title-page subtitle + kicker (the "An Axona <kicker>" line).
subtitle_for() {
  case "$1" in
    Quick-Start-*)            echo "A Working Pub/Sub Roundtrip in Five Minutes";;
    Axona-Programmer-Guide-*) echo "Building Applications That Have No Server";;
    Axona-API-Reference-*)    echo "Every Public Symbol, Exactly";;
    Axona-Services-Guide-*)   echo "Bridges, Relays, and the Programs You Run";;
    Axona-AI-Grounding-*)     echo "Machine-Oriented Grounding for AI-Built Apps";;
    *)                        echo "";;
  esac
}
kicker_for() {
  case "$1" in
    Quick-Start-*)            echo "Quick Start";;
    Axona-Programmer-Guide-*) echo "Programmer Guide";;
    Axona-API-Reference-*)    echo "API Reference";;
    Axona-Services-Guide-*)   echo "Services Guide";;
    Axona-AI-Grounding-*)     echo "AI Grounding";;
    *)                        echo "Document";;
  esac
}

for d in "${DOCS[@]}"; do
  echo "→ $d"
  ver="${d##*-}"                       # trailing -vX.Y.Z of the basename
  tp=".titlepage-$d.tex"
  cat > "$tp" <<EOF
% Generated by render.sh — the explainer-style title page.
\thispagestyle{empty}
\null\vfill
\begin{center}
{\fontsize{48}{52}\selectfont \textsc{Axona}\par}
\vspace{0.6em}
{\Large\itshape $(subtitle_for "$d")\par}
\vspace{4em}
{\large David A.~Smith\par}
{\itshape\small Axona.net\par}
\vspace{2em}
{\small The Axona $(kicker_for "$d") \quad $ver \quad $DATE\par}
\end{center}
\vfill
\null
\newpage
\pagestyle{ndhtplain}
\thispagestyle{ndhtplain}
\setcounter{page}{1}
EOF
  pandoc "$d.md" -o "$d.tex" -s --top-level-division=section \
    -V documentclass=tufte-handout -V classoption=nobib \
    -H axona-doc-preamble.tex -B "$tp"
  tectonic "$d.tex"
  rm -f "$tp"
done
echo "done"
